name: Download SVG files

on:
  workflow_dispatch:


jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Download 
      run: |
        cd images
        chmod +x ../download.sh
        ../download.sh
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        cd images
        git add .
        git diff-index --quiet --cached HEAD || git commit -m "Image Download"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
