name: Download SVGs

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download 
      run: |
        cd images
        curl --fail -o stats.svg https://github-readme-stats.vercel.app/api?username=dan-mba&show_icons=true&title_color=006db0&icon_color=006db0
        curl --fail -o langs.svg https://github-readme-stats.vercel.app/api/top-langs/?username=dan-mba&hide=C%23&title_color=006db0
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add stats.svg langs.svg
        git diff-index --quiet --cached HEAD || git commit -m "Build Action"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
