name: Download SVG files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download 
      run: |
        cd images
        curl --silent -o stats.svg "https://github-readme-stats.vercel.app/api?username=dan-mba&show_icons=true&title_color=006db0&icon_color=006db0"
        curl --silent -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=dan-mba&layout=compact&hide=C%23&title_color=006db0"
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        cd images
        git add --ignore-errors stats.svg langs.svg
        git diff-index --quiet --cached HEAD || git commit -m "Build Action"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
